=== api-evangelist/craft-io/json-schema/craft-io-basefeedbackitem-schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$id": "https://raw.githubusercontent.com/api-evangelist/craft-io/main/json-schema/craft-io-basefeedbackitem-schema.json",
  "title": "BaseFeedbackItem",
  "properties": {
    "id": {
      "type": "string"
    },
    "portalId": {
      "type": "string"
    },
    "shortId": {
      "type": "string"
    },
    "title": {
      "type": "string"
    },
    "description": {
      "type": "string"
    },
    "creationTime": {
      "type": "string",
      "format": "date-time"
    },
    "category": {
      "$ref": "#/components/schemas/Category"
    },
    "owner": {
      "$ref": "#/components/schemas/Person"
    },
    "createdBy": {
      "$ref": "#/components/schemas/Person"
    },
    "status": {
      "$ref": "#/components/schemas/Entity"
    },
    "internalStatus": {
      "$ref": "#/components/schemas/Entity"
    },
    "importance": {
      "$ref": "#/components/schemas/Entity"
    },
    "labels": {
      "items": {
        "type": "string"
      },
      "type": "array"
    },
    "customFields": {
      "items": {
        "$ref": "#/components/schemas/CustomFieldValue"
      },
      "type": "array"
    },
    "linkedItems": {
      "$ref": "#/components/schemas/NullableType_LinkedItem-Array_"
    },
    "webUrl": {
      "type": "string",
      "description": "Direct link into the feedback portal for this feedback item."
    }
  },
  "required": [
    "id"
  ],
  "type": "object",
  "additionalProperties": false
}

=== api-evangelist/craft-io/examples/craft-io-getidea-200-example.json
[
  {
    "id": "2305843010159177973",
    "portalId": "2305843009928936739",
    "shortId": "DAR-6",
    "title": "1",
    "description": "qdw",
    "category": {
      "id": "2305843009943746454",
      "name": "1"
    },
    "status": {
      "id": "2305843009928936743",
      "name": "New"
    },
    "internalStatus": {
      "id": "2305843009943114957",
      "name": "Not a Priority"
    },
    "importance": {
      "id": "2305843009928936757",
      "name": "Nice to Have"
    },
    "creationTime": "2022-06-16T17:06:30.000Z",
    "createdBy": {
      "id": "2305843009550306942",
      "name": "John Doe"
    },
    "owner": {
      "id": "2305843009550306943",
      "name": "Jane Doe"
    },
    "labels": [
      "Label 1",
      "Label 2"
    ]
  }
]
